name: Build macOS Application

on:
  push:
    branches: [ main, master ] # Triggers the workflow on push events to main or master branch

jobs:
  build:
    runs-on: macos-12 # Use a stable macOS version for building

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run build script
      run: |
        chmod +x build_app.sh
        ./build_app.sh
      working-directory: . # Run from the project root

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacOS-App
        path: dist/ThroughputAnalyzer.app # Path to the generated .app folder