name: Build macOS Application

on:
  push:
    branches: [ main, master ] # Triggers the workflow on push events to main or master branch

jobs:
  build:
    runs-on: macos-latest # Use the latest available macOS version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Run build script
      run: |
        chmod +x build_app.sh
        ./build_app.sh
      working-directory: .

    - name: Debug - List files in output directory
      run: ls -R dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MacOS-App
        path: dist/ThroughputAnalyzer.app # Path to the generated .app folder